update antpool.php
Elompenta/antpool-php-api pull request #9
Opened 2017-12-18 12:58 UTC by xslugx

add option for different coins instead of default BTC

2017-12-20 13:00 UTC, Elompenta commented on classes/antpool.php
> +		$coin = '';
see my comment in pull request

2017-12-20 13:01 UTC, Elompenta commented
$coin is not a global variable so it doesnt work.
I think it is better if we change

`function get($type) {`

to 

`function get($type, $currency) {`

so you are able to request more than one currency with one instance of  the antpool api.

2017-12-20 13:14 UTC, xslugx commented
Ok perfect, I wasn't sure how to do that specifically, but on using your code I had to figure out the implementation so that works for me

2017-12-20 13:17 UTC, Elompenta commented
your version is fair enough for one setup, and the ide ais good!
I will check it, an provide a full functionally version with multi currency support.

thanks for your input

2017-12-20 13:20 UTC, xslugx commented
I need to make a change to the custom.php due to bootstrap, I need to add flex to make it work with mobile better

2017-12-20 13:25 UTC, Elompenta commented
@xslugx 
>I need to make a change to the custom.php due to bootstrap, I need to add flex to make it work with mobile better

Do it! ;)
Feel free to improve this class
I will review your changes and commit them to the master branch.

thanks so far

2018-01-18 21:45 UTC, Elompenta commented on classes/antpool.php
> +		$coin = '';
$coin is not a global variable so it doesnt work.
 I think it is better if we change
function get($type) {
to
function get($type, $currency) {
so you are able to request more than one currency with one instance of the antpool api.

2018-01-18 21:46 UTC, Elompenta requested changes
very nice idea - but currency hardcoded in class is not agile enough.

2018-01-18 22:31 UTC, Elompenta commented
nice - i have already commited some minutes before a new Version ;)
Commit: https://github.com/Elompenta/antpool-php-api/commit/4bee623ace095a24422f5eea60f972746640ae34

I have integraed your changes and updated ssl version and readme
i will merge them to the master trunk

@xslugx also you are listed in the readme as contibutor :_}

2018-01-18 22:32 UTC, Elompenta approved these changes

2018-01-18 22:32 UTC, Elompenta commented
changes already commited via branch pr/9

2018-01-18 22:32 UTC, closed without merging